language: php
php:
  - 5.4
  - 5.5
before_script:
  ## Composer
  - composer install
  ## travis configuration
  - cp app/config/config.ini-travis app/config/config.ini
  ## Atoum
  - mkdir -p build/logs
script:
  - php vendor/atoum/atoum/bin/atoum -d tests/units/ -c .atoum.php
  - vendor/bin/php-cs-fixer --diff --dry-run -v fix
after_script:
  - php vendor/bin/coveralls
notifications:
  email:
    on_success: always
    on_failure: always
